### ISSUE TITLE
Validate importing URL as a proper URI

### ISSUE THREAD

**Issue by Suika** [thatfuckingbird/hydownloader#6]
```python
Processing file: gallery-dl/sankaku/screen_capture/sankaku_24868586_8f1e17b5cfd849998090993e2a5217b2.png...
File matched: gallery-dl/sankaku/screen_capture/sankaku_24868586_8f1e17b5cfd849998090993e2a5217b2.png...
Generated URLs:
https://beta.sankakucomplex.com/post/show/24868586
Haitoku no Kyoukai - Episode 2
https://chan.sankakucomplex.com/post/show/24868586
Generated tags:
...
Hashing...
File is already in Hydrus
Associating URLs...
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/hydrus/__init__.py", line 183, in _api_request
    response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://hydrusclient:45869/add_urls/associate_url

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/hydownloader-importer", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/hydownloader/importer.py", line 445, in main
    cli()
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/hydownloader/importer.py", line 427, in run_job
    if do_it: client.associate_url(hashes=[hexdigest],add=list(generated_urls))
  File "/usr/lib/python3.9/site-packages/hydrus/__init__.py", line 383, in associate_url
    self._api_request("POST", self._ASSOCIATE_URL_ROUTE, json=json_)
  File "/usr/lib/python3.9/site-packages/hydrus/__init__.py", line 186, in _api_request
    raise MissingParameter(response)
hydrus.MissingParameter: URL "Haitoku no Kyoukai - Episode 2" was not recognised--did you forget the http:// or https://?

```

**Comment by thatfuckingbird** [comment]
done in c82cfb94ae64c01ab9eb445d50e7d532d6b98c8c, these can be added as tags instead now
